global with sharing class firstApex {
    global firstApex() {
        // addding change for cehck delta deploy
        //adding change for check scanner part of yml files
        System.debug('addding change for cehck delta deploy');
        // Account acc = new Account();
        //for(integer i = 1; i<= 10 ; i++){
           // System.debug('check value of i = ' + [select id from Account limit 1] );
        //}
    }
    
    global static String nothing() {
        return null;
    }
}