name: SFDX Test Run on Push

on:
  pull_request:
    branches: [ staging ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Update npm
        run: npm install -g npm@latest
      - name: "install app and create delta"
        run: |
          echo y | sfdx plugins:install sfdx-git-delta@latest
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git checkout -b pr
          git --no-pager diff --name-status pr origin/staging
          sfdx sgd:source:delta --to pr --from origin/staging --output .
          cat package/package.xml
      - name: "install scanner and check changes"
        run: | 
          echo "Installing JDK"
          sudo apt-get install openjdk-8-jdk
          echo "Install SFDX Scanner"
          echo -e 'y/n' | sfdx plugins:install @salesforce/sfdx-scanner
          echo "Running SFDX Scanner"
          npx sfdx scanner:run --target "**/default/**" --format "csv" --outfile "sfdxScannerAnalysis.csv" --violations-cause-error
      - name: 'Convert Metadata'
        run: sfdx force:source:convert --manifest=package/package.xml --outputdir=convert
      - name: 'Run Test on Metadata'
        run: sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -w30