name: SFDX Test Run on Push

on:
  pull_request:
    branches: [ staging ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      SFDX_DISABLE_DNS_CHECK: true
    
    steps:
      - uses: actions/checkout@v2
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - name: "install app and create delta"
        run: |
          echo y | sfdx plugins:install sfdx-git-delta@latest
          git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
          git fetch --all
          git checkout -b pr
          git --no-pager diff --name-status pr origin/staging
          sfdx sgd:source:delta --to pr --from origin/staging --output .
          cat package/package.xml
      - name: "install scanner and check changes"
        run: | 
          wget https://developer.salesforce.com/media/salesforce-cli/sf/channels/stable/sf-linux-x64.tar.xz
          mkdir -p ~/cli/sf
          tar xJf sf-linux-x64.tar.xz -C ~/cli/sf --strip-components 1
          export PATH=~/cli/sf/bin:$PATH
          echo "$PATH" >> $GITHUB_PATH
          echo "Installing JDK"
          sudo apt-get install openjdk-8-jdk
          echo "Install SFDX Scanner"
          echo -e 'y/n' | sfdx plugins:install @salesforce/sfdx-scanner
          echo "sfdx scanner installed"
      - name: "run scanner"
        run: |
          echo "Running SFDX Scanner"
          sfdx scanner:run --target "force-app" --format "csv" --outfile "scanner-result.csv"
      - name: 'Convert Metadata'
        run: sfdx force:source:convert --manifest=package/package.xml --outputdir=convert
      - name: 'Run Test on Metadata'
        run: sfdx force:mdapi:deploy --deploydir=convert --testlevel=RunLocalTests --checkonly -w30